name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-15
    strategy:
      matrix:
        platform: ['iOS_18', 'iPadOS_17']
      fail-fast: false
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.6.app/Contents/Developer
      - name: Bundle Install
        run: bundle install
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} `which xcpretty`
      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Test Results
          path: .build/derivedData/**/Logs/Test/*.xcresult
  pod-lint:
    name: Lint Pod
    runs-on: macOS-15
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.6.app/Contents/Developer
      - name: Lint Podspec
        run: bundle exec pod lib lint --verbose --fail-fast --swift-version=6.0
  spm-5:
    name: SPM Build
    runs-on: macOS-14
    strategy:
      matrix:
        platform: ['iOS_17']
      fail-fast: false
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_15.4.app/Contents/Developer
      - name: Build
        run: Scripts/build.swift spm ${{ matrix.platform }} `which xcpretty`
  spm-6:
    name: SPM Build
    runs-on: macOS-15
    strategy:
      matrix:
        platform: ['iOS_18']
      fail-fast: false
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.6.app/Contents/Developer
      - name: Build
        run: Scripts/build.swift spm ${{ matrix.platform }} `which xcpretty`
